title: AI Conference Deadlines
description: Countdowns to top CV/NLP/ML/Robotics/AI conference deadlines
author: Abhishek Das

domain: ""
baseurl: ""

twitter_hashtag: machinelearning
github_username: jearyana
github_repo: rgva-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
